apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: stalwart-edge
  namespace: stalwart-edge
spec:
  endpointSelector:
    matchLabels:
      app: stalwart-edge
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "25"
              protocol: TCP
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "25"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: uptime-kuma
            k8s:app: uptime-kuma
      toPorts:
        - ports:
            - port: "25"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: stalwart
            k8s:app: stalwart
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: manafishrov-stalwart
            k8s:app: stalwart
      toPorts:
        - ports:
            - port: "24"
              protocol: TCP
            - port: "443"
              protocol: TCP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "25"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
