apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-stalwart-edge-0
  namespace: stalwart-edge
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-ha
  volumeName: pvc-eb11adef-5e42-40af-a01a-6f6059f6fc78
  resources:
    requests:
      storage: 20Gi
