apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tofu-base
patches:
  - target:
      kind: Terraform
      name: tofu-base
    patch: |
      - op: replace
        path: /metadata/name
        value: mattermost
  - target:
      kind: Terraform
      name: mattermost
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: mattermost
      spec:
        approvePlan: ""
        path: ./gitops/espresso/tofu/mattermost
        backendConfig:
          secretSuffix: mattermost
        varsFrom:
          - kind: Secret
            name: mattermost-tofu
            varsKeys:
              - mattermost_admin_token
              - mattermost_admin_username
        writeOutputsToSecret:
          name: mattermost-outputs
          outputs:
            - alertmanager_webhook_url
            - hermes_home_channel_id
            - hermes_allowed_channel_ids
            - hermes_free_response_channel_ids
