apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - secrets-source.yaml
  - manafishrov-source.yaml
  - manafishrov-secrets-source.yaml
  - infrastructure-controllers.yaml
  - infrastructure-configs.yaml
  - infrastructure-secrets.yaml
  - netbird-operator.yaml
  - netbird-cluster-proxy.yaml
  - apps.yaml
  - apps-secrets.yaml
  - manafishrov.yaml
  - manafishrov-secrets.yaml
