apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manafishrov-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: manafishrov
  decryption:
    provider: sops
    secretRef:
      name: sops-age-manafishrov
  interval: 10m
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: manafishrov-secrets
  serviceAccountName: manafishrov
