apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbird-operator
  namespace: netbird
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
  ref:
    tag: "0.7.0"
    digest: sha256:71a41711215fcb793d9be19e902aa3af87736ce8614acf2b604641084432f33e
