apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbird-operator
  namespace: netbird
spec:
  interval: 1h0m0s
  url: oci://ghcr.io/netbirdio/helm-charts/netbird-operator
  ref:
    tag: "0.8.0"
    digest: sha256:d836ce83f06e7749f826a2ebe680bbec17a9545c7ed4645c4d6217a472d94b8d
