apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tofu-base
patches:
  - target:
      kind: Terraform
      name: tofu-base
    patch: |
      - op: replace
        path: /metadata/name
        value: postgres
  - target:
      kind: Terraform
      name: postgres
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: postgres
      spec:
        path: ./gitops/espresso/tofu/postgres
        backendConfig:
          secretSuffix: postgres
        varsFrom:
          - kind: Secret
            name: postgres-admin
            varsKeys:
              - POSTGRES_USER:pg_admin_user
              - POSTGRES_PASSWORD:pg_admin_password
          - kind: Secret
            name: postgres-passwords
            varsKeys:
              - nextcloud_db_password
              - immich_db_password
              - hindsight_db_password
              - mattermost_db_password
              - mealie_db_password
        writeOutputsToSecret:
          name: postgres-outputs
          outputs:
            - nextcloud_db_password
            - immich_db_password
            - hindsight_db_password
            - hindsight_db_password_urlencoded
            - mattermost_db_password
            - mattermost_db_password_urlencoded
            - mealie_db_password
