apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: tofu-controller
      version: "0.16.3"
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 10
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: v0.16.3@sha256:b8632592cd6674517e36cb412c856cdc77c3a6f6b16e42af030f683f16178d99
      serviceAccount:
        create: true
        allowedNamespaces:
          - flux-system
    allowCrossNamespaceRefs: true
