apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: tofu-controller
      version: "0.16.4"
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 10
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    runner:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: v0.16.4@sha256:fc3af4d9b99f54cc92d4aec51d83117dcf373b79d8ed1dc6f69a4ac154184725
      serviceAccount:
        create: true
        allowedNamespaces:
          - flux-system
    allowCrossNamespaceRefs: true
