apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: gateway-ingress-traffic
spec:
  endpointSelector:
    matchExpressions:
      - key: reserved:ingress
        operator: Exists
  ingress:
    - fromEntities:
        - cluster
        - host
        - remote-node
        - world
  egress:
    - toEntities:
        - cluster
    - toCIDRSet:
        - cidr: 10.0.187.1/32
