apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hermes-agent
  - cliproxyapi
  - hindsight
  - immich
  - media
  - minecraft
  - netbird
  - nextcloud
  - ollama
  - pocket-id
  - mattermost
  - mealie
  - searxng
  - stalwart
  - uptime-kuma
