apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hermes-agent
  - immich
  - media
  - minecraft
  - netbird
  - nextcloud
  - ollama
  - pocket-id
  - signal
  - stalwart
  - uptime-kuma
