apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../manafishrov-tofu-base
patches:
  - target:
      kind: Terraform
      name: manafishrov-base
    patch: |
      - op: replace
        path: /metadata/name
        value: manafishrov-postgres
  - target:
      kind: Terraform
      name: manafishrov-postgres
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: manafishrov-postgres
      spec:
        path: ./tofu/postgres
        backendConfig:
          secretSuffix: manafishrov-postgres
        varsFrom:
          - kind: Secret
            name: postgres-admin
            varsKeys:
              - POSTGRES_USER:pg_admin_user
              - POSTGRES_PASSWORD:pg_admin_password
          - kind: Secret
            name: manafishrov-nextcloud-db
            varsKeys:
              - manafishrov_nextcloud_db_password
          - kind: Secret
            name: manafishrov-twenty-db
            varsKeys:
              - manafishrov_twenty_db_password
        writeOutputsToSecret:
          name: manafishrov-postgres-outputs
          outputs:
            - manafishrov_nextcloud_db_password
            - manafishrov_twenty_db_password
