apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tofu-base
patches:
  - target:
      kind: Terraform
      name: tofu-base
    patch: |
      - op: replace
        path: /metadata/name
        value: database
  - target:
      kind: Terraform
      name: database
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: database
      spec:
        path: ./gitops/espresso/tofu/database
        backendConfig:
          secretSuffix: database
        varsFrom:
          - kind: Secret
            name: postgres-admin
            varsKeys:
              - POSTGRES_USER:pg_admin_user
              - POSTGRES_PASSWORD:pg_admin_password
          - kind: Secret
            name: database-passwords
            varsKeys:
              - nextcloud_db_password
              - immich_db_password
        writeOutputsToSecret:
          name: database-outputs
          outputs:
            - nextcloud_db_password
            - immich_db_password
