apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tofu-base
patches:
  - target:
      kind: Terraform
      name: tofu-base
    patch: |
      - op: replace
        path: /metadata/name
        value: pocket-id-infra
  - target:
      kind: Terraform
      name: pocket-id-infra
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: pocket-id-infra
      spec:
        path: ./gitops/espresso/tofu/pocket-id
        backendConfig:
          secretSuffix: pocket-id-infra
        varsFrom:
          - kind: Secret
            name: pocket-id-credentials
        writeOutputsToSecret:
          name: pocket-id-outputs
          outputs:
            - nextcloud_pocketid_client_id
            - nextcloud_pocketid_client_secret
            - immich_pocketid_client_id
            - immich_pocketid_client_secret
            - immich_config_json
            - mealie_pocketid_client_id
            - mealie_pocketid_client_secret
