apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pocket-id-data-backup
  namespace: pocket-id
spec:
  sourcePVC: data-pocket-id-0
  trigger:
    schedule: "10 2 * * *"
  restic:
    repository: freddo-restic-pocket-id-data
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    copyMethod: Snapshot
    volumeSnapshotClassName: mayastor-snapshot
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
