apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tofu-base
patches:
  - target:
      kind: Terraform
      name: tofu-base
    patch: |
      - op: replace
        path: /metadata/name
        value: honcho-infra
  - target:
      kind: Terraform
      name: honcho-infra
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: honcho-infra
      spec:
        path: ./gitops/espresso/tofu/honcho
        backendConfig:
          secretSuffix: honcho-infra
        varsFrom:
          - kind: Secret
            name: postgres-admin
            varsKeys:
              - POSTGRES_USER:pg_admin_user
              - POSTGRES_PASSWORD:pg_admin_password
