apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mattermost
  namespace: mattermost
spec:
  endpointSelector:
    matchLabels:
      app: mattermost
  ingress:
    - fromEntities:
        - ingress
        - host
        - remote-node
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8065"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: hermes-agent
            k8s:app: hermes-agent
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            k8s:app.kubernetes.io/name: alertmanager
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: uptime-kuma
            k8s:app: uptime-kuma
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: flux-system
      toPorts:
        - ports:
            - port: "8065"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: postgres
            k8s:app: postgres
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
