apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - backup.yaml
  - rbac.yaml
  - configmap.yaml
  - statefulset.yaml
  - honcho-deployments.yaml
  - services.yaml
  - network-policy.yaml
  - honcho-network-policy.yaml
  - httproute.yaml
