apiVersion: netbird.io/v1alpha1
kind: SetupKey
metadata:
  name: hermes-egress
  namespace: hermes-agent
spec:
  name: hermes-egress
  allowExtraDnsLabels: false
  autoGroups:
    - name: Hermes Egress
  ephemeral: true
---
apiVersion: netbird.io/v1alpha1
kind: SidecarProfile
metadata:
  name: hermes-egress
  namespace: hermes-agent
spec:
  setupKeyRef:
    name: hermes-egress
  podSelector:
    matchLabels:
      app: hermes-agent
  injectionMode: Sidecar
