apiVersion: netbird.io/v1alpha1
kind: SetupKey
metadata:
  name: hermes-egress
  namespace: hermes-agent
spec:
  name: hermes-egress
  allowExtraDnsLabels: false
  autoGroups:
    - name: Hermes Egress
  ephemeral: true
---
apiVersion: netbird.io/v1alpha1
kind: SidecarProfile
metadata:
  name: hermes-egress
  namespace: hermes-agent
spec:
  setupKeyRef:
    name: hermes-egress
  podSelector:
    matchLabels:
      app: hermes-agent
  injectionMode: Sidecar
  containerOverride:
    image: netbirdio/netbird:0.78.1@sha256:c0b492f320e1251ac0655e785fa288e935a0b7b16365d14fdcbc8bf75dc5b0a0
    env:
      - name: NB_SETUP_KEY
        valueFrom:
          secretKeyRef:
            name: setup-key-hermes-egress
            key: setup-key
      - name: NB_MANAGEMENT_URL
        value: https://netbird.asgard.michaelbrusegard.com
      - name: NB_LOG_FILE
        value: console
      - name: NB_DISABLE_PROFILES
        value: "true"
      - name: NB_DISABLE_UPDATE_SETTINGS
        value: "false"
      - name: NB_DISABLE_DNS
        value: "true"
      - name: NB_FORCE_RELAY
        value: "true"
      - name: NB_HOSTNAME
        value: hermes-agent
      - name: NB_DAEMON_ADDR
        value: unix:///var/run/netbird/netbird.sock
      - name: NB_ENTRYPOINT_SERVICE_TIMEOUT
        value: "0"
