apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: netbird-data-backup
  namespace: netbird
spec:
  sourcePVC: data-netbird-server-0
  trigger:
    schedule: "20 2 * * *"
  restic:
    repository: freddo-restic-netbird-pvc
    retain:
      within: 100y
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
    copyMethod: Snapshot
    volumeSnapshotClassName: mayastor-snapshot
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
