apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup.yaml
  - server-statefulset.yaml
  - signal-deployment.yaml
  - relay-deployment.yaml
  - coturn-deployment.yaml
  - dashboard-deployment.yaml
  - services.yaml
  - httproute.yaml
  - network-policy.yaml
