apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-relay
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-relay
  template:
    metadata:
      labels:
        app: netbird-relay
    spec:
      containers:
        - name: relay
          image: netbirdio/relay:0.68.3@sha256:5435e687957c0a296da841ba47d163e523ff430d50bfe96923b56d6a889037a9
          env:
            - name: NB_LOG_LEVEL
              value: info
            - name: NB_LISTEN_ADDRESS
              value: ":33080"
          envFrom:
            - secretRef:
                name: netbird-relay-env
          ports:
            - containerPort: 33080
              name: relay
