apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-relay
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-relay
  template:
    metadata:
      labels:
        app: netbird-relay
      annotations:
        secret.reloader.stakater.com/reload: netbird-relay-env
    spec:
      containers:
        - name: relay
          image: netbirdio/relay:0.72.2@sha256:fec7207dd5178a273631136cb2d252b38e35cd8cb385450f00ae540c45be5940
          env:
            - name: NB_LOG_LEVEL
              value: info
            - name: NB_LISTEN_ADDRESS
              value: ":33080"
          envFrom:
            - secretRef:
                name: netbird-relay-env
          ports:
            - containerPort: 33080
              name: relay
