apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-relay
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-relay
  template:
    metadata:
      labels:
        app: netbird-relay
      annotations:
        secret.reloader.stakater.com/reload: netbird-relay-env
    spec:
      containers:
        - name: relay
          image: netbirdio/relay:0.79.0@sha256:0ef3133050c7c5e596ba068d916d3e0f1675ac646d3d169e081331ef3ad2055e
          env:
            - name: NB_LOG_LEVEL
              value: info
            - name: NB_LISTEN_ADDRESS
              value: ":33080"
          envFrom:
            - secretRef:
                name: netbird-relay-env
          ports:
            - containerPort: 33080
              name: relay
