apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netbird-server
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-server
  serviceName: netbird-server-internal
  template:
    metadata:
      labels:
        app: netbird-server
    spec:
      containers:
        - name: management
          image: netbirdio/management:0.70.2@sha256:d6f0f5dca8d60bdcfa7081de9dbf8a0846be8dbd04f6e84020eb5a89686feed1
          args:
            - --port
            - "80"
            - --log-file
            - console
            - --log-level
            - info
            - --disable-anonymous-metrics=true
          ports:
            - containerPort: 80
              name: http
            - containerPort: 9090
              name: metrics
          startupProbe:
            httpGet:
              path: /api/instance
              port: http
            periodSeconds: 10
            failureThreshold: 18
          livenessProbe:
            httpGet:
              path: /api/instance
              port: http
          readinessProbe:
            httpGet:
              path: /api/instance
              port: http
          volumeMounts:
            - mountPath: /etc/netbird/management.json
              name: config
              subPath: management.json
            - mountPath: /var/lib/netbird
              name: data
      volumes:
        - name: config
          secret:
            secretName: netbird-server-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nvme-ha
