apiVersion: v1
kind: Service
metadata:
  name: netbird-server-internal
  namespace: netbird
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: netbird-server
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: stun
    - name: health
      port: 9000
      targetPort: health
    - name: metrics
      port: 9090
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-server
  namespace: netbird
  annotations:
    lbipam.cilium.io/ips: 10.0.188.30,fd7a:115c:a1e0:188::30
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: netbird-server
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: stun
---
apiVersion: v1
kind: Service
metadata:
  name: netbird-dashboard
  namespace: netbird
  annotations:
    lbipam.cilium.io/ips: 10.0.188.31,fd7a:115c:a1e0:188::31
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: netbird-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
