apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-signal
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-signal
  template:
    metadata:
      labels:
        app: netbird-signal
    spec:
      containers:
        - name: signal
          image: netbirdio/signal:0.70.4@sha256:f2ffaf0b184f5fd403d7f65e768778e39dd11c561b60cacb7fefc4c9eb0feffd
          args:
            - --port
            - "10000"
            - --log-file
            - console
            - --log-level
            - info
          ports:
            - containerPort: 10000
              name: signal
