apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-signal
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-signal
  template:
    metadata:
      labels:
        app: netbird-signal
    spec:
      containers:
        - name: signal
          image: netbirdio/signal:0.68.3@sha256:88a635c8619bda483a09eb15bf16e5ca2bd9cf3a13341ca2ee274e3f3e6e4fa0
          args:
            - --port
            - "10000"
            - --log-file
            - console
            - --log-level
            - info
          ports:
            - containerPort: 10000
              name: signal
