apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-signal
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-signal
  template:
    metadata:
      labels:
        app: netbird-signal
    spec:
      containers:
        - name: signal
          image: netbirdio/signal:0.78.1@sha256:ebc42056ce135b5163554fad47c5b1456673e7132dc4fad9f9cc34d84c70feb4
          args:
            - --port
            - "10000"
            - --log-file
            - console
            - --log-level
            - info
          ports:
            - containerPort: 10000
              name: signal
