apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - statefulset.yaml
  - services.yaml
  - network-policy.yaml
  - alertmanager-bridge-configmap.yaml
  - alertmanager-bridge-deployment.yaml
  - alertmanager-bridge-service.yaml
  - alertmanager-bridge-network-policy.yaml
