apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - openebs
  - metrics-server
  - gateway-api
  - coredns
  - kube-prometheus-stack
  - loki
  - alloy
  - rustfs
