apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  serviceName: uptime-kuma-internal
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:2@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
          ports:
            - containerPort: 3001
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 18
          volumeMounts:
            - mountPath: /app/data
              name: data
        - name: autokuma
          image: ghcr.io/bigboot/autokuma:2@sha256:8acbd3ad3ec8cb6c066aa0ee541154921283ec78159015937128541921c47974
          env:
            - name: AUTOKUMA__KUMA__URL
              value: "http://localhost:3001"
            - name: AUTOKUMA__STATIC_MONITORS
              value: "/monitors"
            - name: AUTOKUMA__DOCKER__ENABLED
              value: "false"
          envFrom:
            - secretRef:
                name: uptime-kuma-env
          volumeMounts:
            - mountPath: /monitors
              name: monitors
              readOnly: true
      volumes:
        - name: monitors
          configMap:
            name: uptime-kuma-monitors
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: nvme-ha
