apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-data-backup
  namespace: nextcloud
spec:
  sourcePVC: data-nextcloud-0
  trigger: {}
  restic:
    repository: freddo-restic-nextcloud-data
    moverSecurityContext:
      runAsUser: 33
      runAsGroup: 33
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 5Gi
