apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:9.1.2-alpine@sha256:dd021e69e0a204fbb25b39c332c3dd61d51853d0a67e34f523cf1e1ab15fe478
          args:
            - --maxmemory
            - 256mb
            - --maxmemory-policy
            - allkeys-lru
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - containerPort: 6379
              name: redis
          livenessProbe:
            tcpSocket:
              port: redis
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["valkey-cli", "ping"]
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 320Mi
