apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: cliproxyapi-auth-backup
  namespace: cliproxyapi
spec:
  sourcePVC: auth-cliproxyapi-0
  trigger:
    schedule: "20 2 * * *"
  restic:
    repository: freddo-restic-cliproxyapi-pvc
    pruneIntervalDays: 36500
    retain:
      within: 100y
    moverSecurityContext:
      runAsUser: 10000
      runAsGroup: 10000
    copyMethod: Snapshot
    volumeSnapshotClassName: mayastor-snapshot
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
