apiVersion: v1
kind: ConfigMap
metadata:
  name: cliproxyapi
  namespace: cliproxyapi
data:
  config.yaml: |
    host: ""
    port: 8317
    auth-dir: /data/auths
    api-keys:
      - __API_KEY__
    remote-management:
      allow-remote: true
      secret-key: __MANAGEMENT_KEY__
      disable-control-panel: false
    debug: false
    logging-to-file: false
    usage-statistics-enabled: true
    quota-exceeded:
      switch-project: true
      switch-preview-model: true
