apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cilium
  - dns-tofu
  - flux
  - gateway
  - github-tofu
  - grafana
  - hubble-ui
  - manafishrov-pocket-id-tofu
  - manafishrov-dns-tofu
  - manafishrov-postgres-tofu
  - manafishrov-rustfs-tofu
  - manafishrov-tenant
  - mattermost-tofu
  - netbird
  - netbird-tofu
  - openebs
  - openebs-monitoring
  - pocket-id-tofu
  - postgres-tofu
  - postgres
  - public-dns
  - rustfs
