apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - openebs
  - hubble-ui
  - grafana
  - flux
  - netbird
  - openebs-monitoring
  - manafishrov-tenant
  - cert-manager
  - gateway
  - public-dns
  - rustfs
  - postgres
  - honcho-tofu
  - netbird-tofu
  - pocket-id-tofu
  - manafishrov-storage-tofu
  - manafishrov-dns-tofu
  - manafishrov-identity-tofu
  - manafishrov-database-tofu
