apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - openebs
  - hubble-ui
  - grafana
  - loki
  - flux
  - netbird
  - openebs-monitoring
  - manafishrov
  - cert-manager
  - gateway
  - public-dns
  - homebridge
  - zigbee2mqtt
  - netbird-tofu
