apiVersion: apps/v1
kind: Deployment
metadata:
  name: feishin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feishin
  template:
    metadata:
      labels:
        app: feishin
    spec:
      nodeSelector:
        kubernetes.io/hostname: espresso-1
      containers:
        - name: feishin
          image: ghcr.io/jeffvli/feishin:1.14.0@sha256:752230eccbd2327981bafbf095d8103b751e1a99170ed58262d330dae74aa4c5
          ports:
            - containerPort: 9180
              name: http
          env:
            - name: SERVER_NAME
              value: "Navidrome"
            - name: SERVER_LOCK
              value: "true"
            - name: SERVER_TYPE
              value: "navidrome"
            - name: SERVER_URL
              value: "https://navidrome.asgard.michaelbrusegard.com"
            - name: ANALYTICS_DISABLED
              value: "true"
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
