apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyseerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  serviceName: jellyseerr-internal
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: espresso-1
      initContainers:
        - name: init-config
          image: busybox:1.37@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          command:
            - sh
            - -c
            - chown -R 1000:1000 /app/config
          volumeMounts:
            - mountPath: /app/config
              name: config
      securityContext:
        fsGroup: 1000
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
          ports:
            - containerPort: 5055
              name: http
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Europe/Oslo"
          startupProbe:
            httpGet:
              path: /api/v1/status
              port: http
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/config
              name: config
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: nvme-ha
