apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - shared-pvc.yaml
  - transmission-statefulset.yaml
  - prowlarr-statefulset.yaml
  - radarr-statefulset.yaml
  - sonarr-statefulset.yaml
  - bazarr-statefulset.yaml
  - lidarr-statefulset.yaml
  - navidrome-statefulset.yaml
  - jellyfin-statefulset.yaml
  - jellyseerr-statefulset.yaml
  - flaresolverr-deployment.yaml
  - services.yaml
  - httproutes.yaml
