apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: navidrome
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  serviceName: navidrome-internal
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      nodeSelector:
        kubernetes.io/hostname: espresso-1
      containers:
        - name: navidrome
          image: ghcr.io/navidrome/navidrome:0.62.0@sha256:c4b5cb36a790b3eb63ca6a68bbe2fe149c2d7fa2e586f7a480e61db630e6664b
          ports:
            - containerPort: 4533
              name: http
          env:
            - name: ND_MUSICFOLDER
              value: "/music"
            - name: ND_DATAFOLDER
              value: "/data"
            - name: ND_LOGLEVEL
              value: "info"
            - name: TZ
              value: "Europe/Oslo"
          startupProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /music
              name: media-data
              subPath: media/music
      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: nvme-ha
