apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seerr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  serviceName: seerr-internal
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: seerr-api
      labels:
        app: seerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: espresso-1
      initContainers:
        - name: init-config
          image: busybox:1.38.0@sha256:1cfa4e2b09e127b9c4ed43578d3f3c18e7d44ea47b9ea98475c0cbe9086525f8
          command:
            - sh
            - -c
            - chown -R 1000:1000 /app/config
          volumeMounts:
            - mountPath: /app/config
              name: config
      securityContext:
        fsGroup: 1000
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.4.1@sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1
          ports:
            - containerPort: 5055
              name: http
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Europe/Oslo"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: seerr-api
                  key: API_KEY
          startupProbe:
            httpGet:
              path: /api/v1/status
              port: http
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/config
              name: config
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: nvme-ha
