apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-settings
  namespace: media
data:
  settings-overrides.json: |
    {
      "download-dir": "/data/torrents",
      "incomplete-dir": "/data/torrents/incomplete",
      "incomplete-dir-enabled": true,
      "rpc-whitelist-enabled": false,
      "rpc-bind-address": "::",
      "ratio-limit": 1,
      "ratio-limit-enabled": true,
      "idle-seeding-limit": 1440,
      "idle-seeding-limit-enabled": true
    }
