apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: monitoring
  annotations:
    lbipam.cilium.io/ips: 10.0.188.4,fd7a:115c:a1e0:188::4
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
  ports:
    - name: http
      port: 3100
      targetPort: 3100
