apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: public-records
  namespace: gateway
spec:
  endpoints:
    - dnsName: id.asgard.michaelbrusegard.com
      recordType: CNAME
      targets:
        - router.asgard.michaelbrusegard.com
    # TODO: drop once passkeys are re-registered against id.asgard.
    - dnsName: id.gullhaugveien.michaelbrusegard.com
      recordType: CNAME
      targets:
        - router.asgard.michaelbrusegard.com
    - dnsName: status.asgard.michaelbrusegard.com
      recordType: CNAME
      targets:
        - router.asgard.michaelbrusegard.com
    - dnsName: netbird.asgard.michaelbrusegard.com
      recordType: CNAME
      targets:
        - router.asgard.michaelbrusegard.com
