apiVersion: v1
kind: Namespace
metadata:
  name: manafishrov
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: manafishrov-roundcube
  labels:
    gateway-access: public
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: manafishrov-stalwart
  labels:
    gateway-access: public
    pod-security.kubernetes.io/enforce: baseline
