apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vanilla-world-backup
  namespace: minecraft
spec:
  sourcePVC: data-vanilla-0
  paused: true
  trigger: {}
  restic:
    repository: freddo-restic-minecraft-vanilla
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: creative-world-backup
  namespace: minecraft
spec:
  sourcePVC: data-creative-0
  paused: true
  trigger: {}
  restic:
    repository: freddo-restic-minecraft-creative
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: revelation-world-backup
  namespace: minecraft
spec:
  sourcePVC: data-revelation-0
  paused: true
  trigger: {}
  restic:
    repository: freddo-restic-minecraft-revelation
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
