apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vanilla-statefulset.yaml
  - creative-statefulset.yaml
  - revelation-statefulset.yaml
  - services.yaml
  - mc-router.yaml
  - dns.yaml
  - network-policy.yaml
