{
  inputs,
  lib,
  ...
}: {
  imports = [
    inputs.nixos-raspberrypi.nixosModules.raspberry-pi-4.base
    inputs.nixos-raspberrypi.nixosModules.sd-image
  ];

  hardware.bluetooth.enable = true;
  services.openthread-border-router.radio = {
    device = "/dev/serial/by-id/usb-dresden_elektronik_Thread_RCP__ConBee_II__DE2688235-if00";
    flowControl = true;
  };

  # Impermanence: keep the SD root partition for state, run / from tmpfs.
  fileSystems."/" = lib.mkForce {
    device = "none";
    fsType = "tmpfs";
    options = ["defaults" "mode=755"];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
    options = ["noatime"];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/persistent/nix";
    fsType = "none";
    options = ["bind"];
    neededForBoot = true;
    depends = ["/persistent"];
  };

  # /boot lives on the SD ext4 partition (extlinux.conf is regenerated by the
  # raspberry-pi bootloader builder on every rebuild); keep it persistent.
  fileSystems."/boot" = {
    device = "/persistent/boot";
    fsType = "none";
    options = ["bind"];
    neededForBoot = true;
    depends = ["/persistent"];
  };

  # The sd-image module hands the nix-store DB off to nix-store on first boot
  # from a file on the root partition; point it at the new mount.
  sdImage.nixPathRegistrationFile = "/persistent/nix-path-registration";

  # The default expand-on-boot logic walks `findmnt -n -o SOURCE /`, which now
  # returns the tmpfs. Disable it; the SD partition is sized at flash time.
  sdImage.expandOnBoot = false;
}
