apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../tofu-base
patches:
  - target:
      kind: Terraform
      name: tofu-base
    patch: |
      - op: replace
        path: /metadata/name
        value: netbird-infra
  - target:
      kind: Terraform
      name: netbird-infra
    patch: |
      apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      metadata:
        name: netbird-infra
      spec:
        path: ./gitops/espresso/tofu/netbird
        backendConfig:
          secretSuffix: netbird-infra
        varsFrom:
          - kind: Secret
            name: netbird-credentials
