apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: netbird-infra
  namespace: flux-system
spec:
  path: ./gitops/espresso/tofu/netbird
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  storeReadablePlan: human
  backendConfig:
    secretSuffix: netbird-infra
  varsFrom:
    - kind: Secret
      name: netbird-credentials
  alwaysCleanupRunnerPod: true
