apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-uploads-backup
  namespace: immich
spec:
  sourcePVC: uploads-immich-0
  trigger: {}
  restic:
    repository: freddo-restic-immich-uploads
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
    copyMethod: Snapshot
    volumeSnapshotClassName: mayastor-snapshot
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 5Gi
