apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: machine-learning-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nvme-ha
