apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openebs
  - metrics-server/metrics-server-install.yaml
  - coredns/coredns-config.yaml
  - gateway-api
  - cilium
  - gateway
