apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-ha
provisioner: io.openebs.csi-mayastor
parameters:
  protocol: nvmf
  repl: "3"
  ioTimeout: "60"
  poolAffinityTopologyLabel: |
    openebs.io/disk-type: nvme
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-ha
provisioner: io.openebs.csi-mayastor
parameters:
  protocol: nvmf
  repl: "2"
  ioTimeout: "60"
  poolAffinityTopologyLabel: |
    openebs.io/disk-type: sata
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-single
provisioner: io.openebs.csi-mayastor
parameters:
  protocol: nvmf
  repl: "1"
  ioTimeout: "60"
  poolAffinityTopologyLabel: |
    openebs.io/disk-type: nvme
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
