apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - public-gateway.yaml
  - internal-gateway.yaml
  - public-redirects.yaml
  - macchiato-dns.yaml
  - homebridge.yaml
  - unifi.yaml
  - zigbee2mqtt.yaml
