apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: manafishrov-infra
  namespace: flux-system
spec:
  path: ./tofu
  sourceRef:
    kind: GitRepository
    name: manafishrov
    namespace: flux-system
  interval: 10m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  storeReadablePlan: human
  backendConfig:
    secretSuffix: manafishrov-infra
  varsFrom:
    - kind: Secret
      name: rustfs-secret
      varsKeys:
        - RUSTFS_ACCESS_KEY:rustfs_access_key
        - RUSTFS_SECRET_KEY:rustfs_secret_key
        - firmware_ci_secret_key
    - kind: Secret
      name: manafishrov-pocket-id-credentials
      varsKeys:
        - pocketid_api_token
  runnerPodTemplate:
    spec:
      env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: api-token
  alwaysCleanupRunnerPod: true
  writeOutputsToSecret:
    name: manafishrov-tofu-outputs
    outputs:
      - vaultwarden_pocketid_client_id
      - vaultwarden_pocketid_client_secret
