apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: manafishrov-infra
  namespace: flux-system
spec:
  path: ./tofu
  sourceRef:
    kind: GitRepository
    name: manafishrov
    namespace: flux-system
  interval: 10m
  approvePlan: auto
  destroyResourcesOnDeletion: false
  backendConfig:
    inClusterConfig: true
  varsFrom:
    - kind: Secret
      name: tofu-credentials
  alwaysCleanupRunnerPod: true
